name: First Workflow

on: push

jobs:
  test:
    runs-on: ununtu-latest
    steps:
     - name: Get Code
       uses: actions/checkout@v3
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
        node-version: 18


